### ISSUE TITLE
Error 123 - Filename, directory or volume is incorrect

### ISSUE THREAD

**Issue by NicoleMauserStorer** [IgnoredAmbience/yahoo-group-archiver#113]
First - thank you for tolerating what is probably a very silly question.  I know enough about all of this to be dangerous and have been able to install Python, manage to install requests, find the cookie values and all those pieces and now am stuck on what I'm sure is the easiest part.  

I have:  yahoo.py -ct "<CookieValueHere>" -cy "<SecondCookieValueHere>" "<UMECRA_BoD>"

I get: 

Traceback (most recent call last):
  File "C:\Python27\yahoogroup\yahoo.py", line 690, in <module>
    with Mkchdir(args.group, sanitize=False):
  File "C:\Python27\yahoogroup\yahoo.py", line 559, in __enter__
    os.chdir(self.d)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: '<UMECRA_BoD>'

It looks like this is a file directory issue, so I've created a "UMECRA_BoD" directory in the Python folder and in the YahooGroup folder where the script is, but, still errors.  What am I missing?

Huge thank you as we have something like 15 years of files and communications from an organization that I don't want to download one at a time... YIKES

**Comment by NicoleMauserStorer** [comment]
I do have the cookie values in the appropriate spots - not sure why they aren't showing up on the screen - I have them in quotes and brackets as directed and had put in CookieValue1 and CookieValue2 as generic text for this example - the correct values are in my script

**Comment by foghawk** [comment]
The cookie values and group name should only be in quotes, not angle brackets.

(The brackets are just to clarify that `groupid` is a parameter which you should fill in with the appropriate value and not a literal string that should be copied exactly. It's common to use them in this way.)

The script thinks you're trying to archive the group "&lt;UMECRA_BoD&gt;" instead of "UMECRA_BoD", and Windows is complaining because it doesn't allow the characters `<` and `>` in filenames. Remove the brackets and this will go away.

(As for your text not showing up, GitHub gets confused about angle brackets because it thinks you're trying to write HTML. Type backticks (`` ` ``) around your command, or three backticks (`` ``` ``) before and after the whole error message, to stop GitHub from trying to format it. Details [here](https://guides.github.com/features/mastering-markdown/).)

**Comment by IgnoredAmbience** [comment]
Yes, the angular brackets were an indication of what text to change in the command line rather needing to include them as part of the group name. I've removed them from the readme, hopefully this is now clearer.
