### ISSUE TITLE
Yahoo is having trouble opening accented folders or files (invalid path)

### ISSUE THREAD

**Issue by lrrosa** [IgnoredAmbience/yahoo-group-archiver#13]
Yahoo is having trouble opening accented folders or files. It's a problem with Yahoo servers.
But when yahoo-group-archiver tries to download one of those files/folders it crashes.

"httpStatus":200,"errorMessage":"Invalid path","errorCode":1309

Traceback (most recent call last):
  File "./yahoo.py", line 195, in <module>
    archive_files(yga)
  File "./yahoo.py", line 96, in archive_files
    archive_files(yga, subdir=pathURI)
  File "./yahoo.py", line 73, in archive_files
    file_json = yga.files(sfpath=subdir)
  File "/root/yahoo-group-archiver/yahoogroupsapi.py", line 83, in get_json
    raise e
KeyError: 'ygData'

**Comment by cas206** [comment]
httpStatus":200,"errorMessage":"Invalid path","errorCode":1309

Same error, different reason.  In my case, clicking on the folder in Yahoo groups gives an invalid path error, as well.  So the path is broke at the source.  I would like either default behavior to skip and go to the next, or a command line tag to enable skipping of invalid paths.

**Comment by IgnoredAmbience** [comment]
Could you give an example of a group (if public) that shows this bug so that I may test a fix?

**Comment by WarriorsLance** [comment]
This public group has several album names with characters (# " ;) not allowed in file or path names.  The download keeps crashing the yahoo.py script at the 3rd album which contains a " in the album name.  Another group download crashed at the | character but that group is private.  This group below also fails to download all the files due to a " in a file folder name.

BugHLG

**Comment by WarriorsLance** [comment]
Another group crashes the download at a album name like this: Untitled album 01.03.2015, 13:49:35

Of course, the lack of being able to restart at some place in the middle makes it difficult to get all the photos when a group has 3600 photos!  Need some sort of ignore errors switch with a skipped files/photos log.

**Comment by Kuipo** [comment]
My group is private so I can't give you a link, but I have an error when trying to switch to a directory with an ö in the directory name.

* Fetching directory 'V Gröbl' (3/17)

Looking into it a bit more, it looks like it's encoding the name a bit strange?  If I browse to the page, the string is:
/files/Membership%20/2018%20New%20Member%20Applications/V%20Gr%C3%B6bl/

but the script is trying to navigate to:
/files?sfpath=%2FMembership+%2F2018+New+Member+Applications%2FV+Gr%C3%83%C2%B6bl%2F

Some of it is different because it's an API call vs the web interface, but when you decode it the difference is:
/files/Membership /2018 New Member Applications/V Gröbl/
/files?sfpath=/Membership+/2018+New+Member+Applications/V+GrÃ¶bl/

I'm not sure where the extra %83%C2 is coming from but I bet if we can remove it or whatever is adding it then the script would allow special characters.

**Comment by Kuipo** [comment]
I just tried the latest commit and it works now.  Looks like this issue isn't a problem anymore.

**Comment by tripleee** [comment]
Yahoo has a long history of spectacularly bad handling of character encodings. There are several issues, some of which may be reported in #9 which also contains a draft for a (partial?) fix.

**Comment by lrrosa** [comment]
With the last commit (3bd73d6) I no longer have this issue.
