### ISSUE TITLE
Offtopic: Do you know any free online forum that can import the exported yahoo data

### ISSUE THREAD

**Issue by jmeile** [IgnoredAmbience/yahoo-group-archiver#58]
Hi

I'm just wondering if you know any free online forum that can import all the exported data from yahoo. I know: https://groups.io, which will do everything automatically. However, the free version is limited.

Best regards
Josef

**Comment by d235j** [comment]
@jmeile at this time we have been focusing on archiving data. As far as we are aware, no platform other than groups.io is able to import Yahoo data yet.

We are hoping that in the near future, this will change, but right now, due to the impending deletion of all Yahoo Groups archives, our focus is on accurate and complete archival.

**Comment by IgnoredAmbience** [comment]
Any details of a viewer specifically for our archive format will probably appear on #48, please follow that issue for details.
